USE [master]
GO

/****** Object:  Database [ThongTin]    Script Date: 08/12/2019 08:34:37 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'ThongTin')
DROP DATABASE [ThongTin]
GO

USE [master]
GO

/****** Object:  Database [ThongTin]    Script Date: 08/12/2019 08:34:37 ******/
CREATE DATABASE [ThongTin] ON  PRIMARY 
( NAME = N'ThongTin', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ThongTin.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ThongTin_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\ThongTin_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ThongTin] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ThongTin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ThongTin] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ThongTin] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ThongTin] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ThongTin] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ThongTin] SET ARITHABORT OFF 
GO

ALTER DATABASE [ThongTin] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ThongTin] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ThongTin] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ThongTin] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ThongTin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ThongTin] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ThongTin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ThongTin] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ThongTin] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ThongTin] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ThongTin] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ThongTin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ThongTin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ThongTin] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ThongTin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ThongTin] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ThongTin] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ThongTin] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ThongTin] SET  READ_WRITE 
GO

ALTER DATABASE [ThongTin] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ThongTin] SET  MULTI_USER 
GO

ALTER DATABASE [ThongTin] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ThongTin] SET DB_CHAINING OFF 
GO

